// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM6s9R9IfGA9zClQJi5wi2kFFCdqC0B3Q',
    appId: '1:681894348716:android:0780b3c7f3f09a125b5c09',
    messagingSenderId: '681894348716',
    projectId: 'grocery-app-7fb67',
    storageBucket: 'grocery-app-7fb67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbZwCzoU2aG96A2dzY1Q8e38beYAfZGeQ',
    appId: '1:681894348716:ios:9e154f9b76e4b5c25b5c09',
    messagingSenderId: '681894348716',
    projectId: 'grocery-app-7fb67',
    storageBucket: 'grocery-app-7fb67.firebasestorage.app',
    androidClientId: '681894348716-ald4ksrjn87cb25qhcoce48skpogvsij.apps.googleusercontent.com',
    iosClientId: '681894348716-k48avne9ucbm1loq8dc9f5t913k039so.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryApp',
  );

}